apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-app-4g8g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-app-4g8g
    app.kubernetes.io/part-of: my-application
  name: demo-app-4g8g
  namespace: karthik
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: demo-app-4g8g
status:
  loadBalancer: {}
